server:
  port: 8024


spring:
  redis:
    jedis:
      pool:
        max-idle: 1000
        max-wait: 5000
        max-active: 1000
    host: localhost
    port: 6379

logging:
  config: classpath:log4j2.yml


